import { GetServerSideProps } from "next";
import Head from "next/head";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import Movie from "../models/movie";
import requests from "../utils/requestes";

export default function Home({ results }: { results: Movie[] }) {
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Nav />

      <Results movies={results} />
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const genre = context.query.genre as string;

  const url = requests[genre]?.url || requests.fetchTrending.url;

  const res = await fetch(`https://api.themoviedb.org/3${url}`);
  const data = await res.json();

  const movies = data.results as Array<Partial<Movie>>;

  return {
    props: {
      results: movies,
    },
  };
};
